### ISSUE TITLE
have_updateable_fields not able to check if fields are listed as updateable or not

### ISSUE THREAD

**Issue by jkulzer** [G5/jsonapi-resources-matchers#14]
When using the method "have_updateable_fields" the lib does not seem to be able to pull from a jsonapi-resources class to check this value. For example:

> expected #<Api::V2::EntityResource:0x007f880e32cdf8> to respond to `has_updatable_fields?`
> ./spec/resources/entity_spec.rb:13:in `block (2 levels) in <top (required)>'
> -e:1:in `load'
> -e:1:in `<main>'

Unsure if it is this, jsonapi-resources, or the resource defintion itself that is the problem.

The selection from the resource itself is defined as such:

>       def self.updatable_fields(_context)
>         super - [:entity]
>       end

With the check being:

`it { is_expected.to_not have_updatable_fields(:entity) }`

**Comment by ramontayag** [comment]
Sounds like RSpec is not able to find the matcher. Have you added `require 'jsonapi/resources/matchers'` and set `type: :resource` to the spec?

**Comment by jkulzer** [comment]
@ramontayag Thank you for your response, I double checked and have all mentioned required through helper files. Here is more of the full RSpec. I appreciate your assistance.

`require 'rails_helper'

RSpec.describe Api::V2::EntityResource, type: :resource do
  let(:entity) { create(:entity) }
  subject { described_class.new(entity, {}) }

  # Field Accessibility Validation
  it { is_expected.to_not have_updatable_fields(:entity) }
end
`

The require you specify is inside spec_helper, which is defined in the rails_helper file.  I have also attempted to define the require specifically in the RSpec as well to ensure. I'm more than happy to admit I have something configured incorrectly, but unsure what to look for further beyond the require.

Thank you for any information.

**Comment by BatuhanW** [comment]
I had the same problem too, `have_updatable_field` -not fields- matcher works fine!
```ruby
fields = %i[some fields here]

fields.each do |field|
  it { is_expected.to have_updatable_field(field) }
end
```

**Comment by ramontayag** [comment]
Oh... yes. I missed that `s`. Thanks @BatuhanW!

**Comment by jkulzer** [comment]
Hmm. I swear I had tried to use it without the s previously, but doing it again after this thread seems to work. I had grabbed it from the readme on the front page as an example.

Thank you both for the review and for taking the time to answer.
