### ISSUE TITLE
why jsonapi-resources-matchers should test creatable/updatabe/sortable fields against instance 

### ISSUE THREAD

**Issue by Fivell** [G5/jsonapi-resources-matchers#8]
Hello thanks for gem.
Using this gem I found that there are sort of limitation in matchers because they 
 - should be used in context of instance of resource.
 - allow to match only by single attribute

Take a look 
using ```jsonapi-resources-matchers```

```ruby
describe CountryResource, type: :resource do
    let(:context) { Hash.new }
    let(:entity) { FactoryGirl.create(:country) }
    subject { described_class.new(entity, context) }
    # updatable_fields
    it { is_expected.to have_updatable_field(:iso) }
    it { is_expected.to have_updatable_field(:prefix) }
    it { is_expected.to have_updatable_field(:name) }
    it { is_expected.to have_updatable_field(:id) }

    context 'readonly' do 
      let(:context) { Hash.new(readonly: true) }
       # updatable_fields
       it { is_expected.not_to have_updatable_field(:iso) }
       it { is_expected.not_to have_updatable_field(:prefix) }
       it { is_expected.not_to have_updatable_field(:name) }
       it { is_expected.not_to have_updatable_field(:id) }
    end 
end
```

without using ```jsonapi-resources-matchers```

```ruby

describe CountryResource, type: :resource do
   let(:context) { Hash.new }
   describe '.updatable_fields' do
     let(:subject) do 
         described_class.updatable_fields(context)
     end
    it 'should have valid set of fields' do 
         expect(subject).to match_array([:iso, :prefix, :name, :id])
    end

    context 'readonly' do 
        let(:context) { Hash.new(readonly: true) }
        it 'should have valid set of fields' do 
           expect(subject).to match_array([])
        end
    end

end
```

**Comment by ramontayag** [comment]
Hi, sorry for the late reply. This got buried in my inbox. Do you have any suggestions on how we can fix this? :)

**Comment by Fivell** [comment]
@ramontayag , maybe to deprecate this matchers

**Comment by ramontayag** [comment]
Yes, we certainly just check if the array includes the given symbol, just like the test does. I will sleep on this, but yes, I'm leaning towards removing this. Thanks.

**Comment by ramontayag** [comment]
@Fivell I decided to spike a version with the matcher still there. It accepts a list of symbols now, and you still get the benefits of it being short.

With https://github.com/G5/jsonapi-resources-matchers/commit/25b0750ef439387c86464ba174b956410aacdd2d, your example should be:

```ruby
describe CountryResource, type: :resource do
    let(:context) { Hash.new }
    let(:entity) { FactoryGirl.create(:country) }
    subject { described_class.new(entity, context) }
    it { is_expected.to have_updatable_field(:iso, :prefix, :name, :id) }

    context 'readonly' do 
       let(:context) { Hash.new(readonly: true) } 
       it { is_expected.not_to have_updatable_field(:iso, :prefix, :name, :id) }
    end 
end
```

Does it still look useful?

**Comment by Fivell** [comment]
@ramontayag , sure, but problem is that updatable_fields is class method  and not instance one.

**Comment by ramontayag** [comment]
Yes it's defined on the class level. Are you concerned that it looks like
it's being tested on the instance level?

**Comment by ramontayag** [comment]
Underneath, it still calls the class-level method and passes the instance's context into the `updatable_fields` method.

**Comment by Fivell** [comment]
@ramontayag , sure but to test this , I need to create instance , but by design of jsonapi resources I don't need this. So ```jsonapi-resources-matchers``` tells me that I need to test instance instead of class and it's very strange.

**Comment by ramontayag** [comment]
I think I understand what you meant earlier.

It always registered as an instance-level test to me because `context` comes from the resource itself.

I'm not so certain I want to remove this matcher though. If I'll be using other matchers in the gem, without this matcher, I'll have to type more:

```ruby
describe CountryResource, type: :resource do
    let(:context) { Hash.new }
    let(:entity) { FactoryGirl.build_stubbed(:country) }
    subject { described_class.new(entity, context) }
    it { is_expected.to have_attribute(:iso) }
    it { is_expected.to ... }

    # With this matcher:
    it { is_expected.to have_updatable_fields(:iso, :prefix, :name, :id) } # one additional line

    # Without this matcher:
    it "allows updating of specific fields" do
      expect(described_class.updatable_fields(context)).to match_array(*%i[iso prefix name id])
    end
end
```

It also feels like the test shows the way the gems are made more than it should.

Anyway, thanks for bringing this up. :)

**Comment by Fivell** [comment]
@ramontayag , suitable for me since 25b0750
